### PR TITLE
add 'stylesheet' option to 'rel' attribute

### PR DESCRIPTION
**Pull request by marcellus48k**
Hi,

I added one more option to 'rel' attribute: 'stylesheet'

Best.

### CODE REVIEW

**Comment by benogle** [comment]
The `completions.json` file is generated. So this change will get wiped when the `update.coffee` script is run. 

Maybe it's time to pull the [HTML attributes](https://github.com/adobe/brackets/master/src/extensions/default/HTMLCodeHints/HtmlAttributes.json) and [HTML tags](https://raw.githubusercontent.com/adobe/brackets/master/src/extensions/default/HTMLCodeHints/HtmlTags.json) into this repo. Or maybe a new repo with these attributes, that everyone can use?

**Comment by chrisgriffith** [comment]
The issue is since the list of tags and attributes is coming from the Brackets list, you should update that source. I am familiar with that code hinter as well. That hinter can look at the parent tag and supply a different attribute list. There is a general list of rel attributes, but there is a specific list of rel attributes if it is in a link tag.

**Comment by benogle** [comment]
You're right. Looks like we arent parsing the `tag/attr` format, so that should be the fix. 

I started writing something about making a PR on brackets, but it would be nice if these files were pulled out of brackets into a repo that all text editor vendors could maintain.

**Comment by marcellus48k** [comment]
Thanks all. The commit has no sense I close the pull request.

**Pull request closed without merging**
